export const ADD_TO_SELECTED_COLUMNS = 'home/ADD_TO_SELECTED_COLUMNS'
export const REMOVE_SELECTED_COLUMNS = 'home/REMOVE_SELECTED_COLUMNS'
export const ALL_COLUMN_SELECTED = 'home/ALL_COLUMN_SELECTED'
export const NONE_COLUMN_SELECTED = 'home/NONE_COLUMN_SELECTED'

